sudo: required
services:
  - docker

before_install:
  - docker build -t thuriaux/react-test -f client/Dockerfile.dev client/

script:
  - docker run thuriaux/react-test npm run test -- --coverage

after_success:
  - docker build -t thuriaux/multi-client client/
  - docker build -t thuriaux/multi-nginx nginx/
  - docker build -t thuriaux/multi-server server/
  - docker build -t thuriaux/multi-worker worker/
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thuriaux/multi-client
  - docker push thuriaux/multi-server
  - docker push thuriaux/multi-nginx
  - docker push thuriaux/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-ca-central-1-250512644452
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

